---

### SurvivalGames Plugin
### By: Andre_The_Gamer

### Language 

PlayerJoinServer: Welcome To My Server 
ArenaJoin: Joining SG Match...
Arenajoined: You have join {ARENA}
ArenaFullMessage: Tournament Is Full, please try later


### Arena settings

# The world the plugin will use to teleport players to lobby after
# they die, or win a match.

LobbyWorld: Lobby

# The world the plugin will use to teleport the player to
# the arena.

Arena: world

# Player control [CANNOT BE CHANGED YET]

Min_Player: 2
Max_Player: 24


# Stand where you want to set a spawn and do /xyz and add the
# numbers in config
# Add The same line for more player's
Spawns:
- 0, 0, 0
- 5, 5, 5
- 2, 3, 4


---
